// alert-manager.js
const nodemailer = require("nodemailer");
const axios = require("axios");

// Track last alert per endpoint to avoid spam (cooldown: 5 min)
const lastAlertTime = {};
const COOLDOWN_MS = 5 * 60 * 1000;

function shouldAlert(endpointId) {
  const last = lastAlertTime[endpointId];
  if (!last) return true;
  return Date.now() - last > COOLDOWN_MS;
}

function markAlerted(endpointId) {
  lastAlertTime[endpointId] = Date.now();
}

async function sendEmailAlert(endpoint, result) {
  if (process.env.ALERT_EMAIL_ENABLED !== "true") return;
  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const subject = `🚨 SIP Alert: ${endpoint.name} is ${result.status}`;
    const html = `
      <div style="font-family:sans-serif;max-width:520px;margin:auto;">
        <div style="background:#1a1a2e;color:#fff;padding:20px 24px;border-radius:8px 8px 0 0;">
          <h2 style="margin:0;font-size:18px;">🔔 SIP Endpoint Alert</h2>
        </div>
        <div style="border:1px solid #e2e8f0;border-top:none;padding:20px 24px;border-radius:0 0 8px 8px;">
          <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:6px 0;color:#64748b;width:130px;">Endpoint</td><td style="font-weight:600;">${endpoint.name}</td></tr>
            <tr><td style="padding:6px 0;color:#64748b;">Host</td><td style="font-family:monospace;">${endpoint.host}:${endpoint.port}</td></tr>
            <tr><td style="padding:6px 0;color:#64748b;">Status</td><td style="font-weight:700;color:${result.status === "DOWN" ? "#ef4444" : "#f59e0b"};">${result.status}</td></tr>
            <tr><td style="padding:6px 0;color:#64748b;">Response</td><td>${result.code ? `${result.code} ${result.reason}` : result.reason}</td></tr>
            <tr><td style="padding:6px 0;color:#64748b;">Time</td><td>${new Date().toUTCString()}</td></tr>
          </table>
          <p style="margin-top:16px;color:#64748b;font-size:13px;">This alert was generated by SIP Health Monitor. Cooldown: 5 minutes per endpoint.</p>
        </div>
      </div>
    `;

    await transporter.sendMail({
      from: `"SIP Monitor" <${process.env.SMTP_USER}>`,
      to: process.env.ALERT_EMAIL_TO,
      subject,
      html,
    });
    console.log(`[ALERT] Email sent for ${endpoint.name}`);
  } catch (err) {
    console.error(`[ALERT] Email failed:`, err.message);
  }
}

async function sendSlackAlert(endpoint, result) {
  if (process.env.ALERT_SLACK_ENABLED !== "true") return;
  try {
    const icon = result.status === "DOWN" ? "🔴" : "🟡";
    const payload = {
      text: `${icon} *SIP Alert: ${endpoint.name} is ${result.status}*`,
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `${icon} *SIP Endpoint Alert*\n*Endpoint:* ${endpoint.name}\n*Host:* \`${endpoint.host}:${endpoint.port}\`\n*Status:* *${result.status}*\n*Response:* ${result.code ? `${result.code} ${result.reason}` : result.reason}\n*Time:* ${new Date().toUTCString()}`
          }
        }
      ]
    };
    await axios.post(process.env.SLACK_WEBHOOK_URL, payload);
    console.log(`[ALERT] Slack sent for ${endpoint.name}`);
  } catch (err) {
    console.error(`[ALERT] Slack failed:`, err.message);
  }
}

async function sendWebhookAlert(endpoint, result) {
  if (process.env.ALERT_WEBHOOK_ENABLED !== "true") return;
  try {
    await axios.post(process.env.ALERT_WEBHOOK_URL, {
      endpoint: endpoint.name,
      host: endpoint.host,
      port: endpoint.port,
      status: result.status,
      code: result.code,
      reason: result.reason,
      timestamp: new Date().toISOString(),
    });
    console.log(`[ALERT] Webhook sent for ${endpoint.name}`);
  } catch (err) {
    console.error(`[ALERT] Webhook failed:`, err.message);
  }
}

async function triggerAlerts(endpoint, result) {
  if (result.status === "UP") return;
  if (!shouldAlert(endpoint.id)) {
    console.log(`[ALERT] Cooldown active for ${endpoint.name}, skipping.`);
    return;
  }
  markAlerted(endpoint.id);
  await Promise.all([
    sendEmailAlert(endpoint, result),
    sendSlackAlert(endpoint, result),
    sendWebhookAlert(endpoint, result),
  ]);
}

module.exports = { triggerAlerts };
